import { useEffect, useState } from "react";

import { AppShell, Button, Card, Panel } from "@ds/index";

import {
  exportHandoverJson,
  exportHandoverPdf,
  fetchHandoverAnalytics,
  fetchHandoverHistory,
  type HandoverAnalytics,
  type HandoverRecord,
} from "../api/client";
import { useDemoMode } from "../demo/useDemoMode";

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function HandoverHistoryPage() {
  const [demo] = useDemoMode();
  const [items, setItems] = useState<HandoverRecord[]>([]);
  const [analytics, setAnalytics] = useState<HandoverAnalytics | null>(null);
  const [selected, setSelected] = useState<HandoverRecord | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchHandoverHistory()
      .then((payload) => {
        setItems(payload.items);
        setSelected(payload.items[0] || null);
        setError(null);
      })
      .catch((err: Error) => setError(err.message));
    fetchHandoverAnalytics()
      .then(setAnalytics)
      .catch(() => setAnalytics(null));
  }, [demo]);

  async function onExport(kind: "json" | "pdf") {
    if (!selected) return;
    if (kind === "json") {
      const payload = await exportHandoverJson(selected.handover_id);
      downloadBlob(`handover-${selected.handover_id}.json`, new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }));
      return;
    }
    const blob = await exportHandoverPdf(selected.handover_id);
    downloadBlob(`handover-${selected.handover_id}.pdf`, blob);
  }

  const compare = analytics?.compare;
  return (
    <AppShell title="Shift Handover History" operationalStatus="INVESTIGATING">
      <p className="ds-page-lead">Every AI safety briefing, with counts, Slack posting, and how it was generated.</p>
      {error ? (
        <p className="ds-empty" role="alert">
          {error}
        </p>
      ) : null}
      <div className="ds-grid ds-grid--metrics" style={{ marginBottom: 24 }}>
        <Card variant="analytics-card">
          <p className="ds-metric__label">Total Handovers</p>
          <p className="ds-metric__value">{analytics?.total_handovers ?? items.length}</p>
        </Card>
        <Card variant="analytics-card">
          <p className="ds-metric__label">Average Open Incidents</p>
          <p className="ds-metric__value">{analytics?.average_open_incidents ?? 0}</p>
        </Card>
        <Card variant="analytics-card">
          <p className="ds-metric__label">Average Critical Alerts</p>
          <p className="ds-metric__value">{analytics?.average_critical_alerts ?? 0}</p>
        </Card>
        <Card variant="analytics-card">
          <p className="ds-metric__label">Most Common Shift Risks</p>
          <p className="ds-metric__value" style={{ fontSize: "var(--font-size-sm)" }}>
            {analytics?.most_common_shift_risks?.[0]?.label ?? "—"}
          </p>
        </Card>
      </div>
      <Panel title="Compare Shifts" style={{ marginBottom: 24 }}>
        <div className="ds-grid ds-grid--split">
          <Card variant="analytics-card">
            <h3>Morning Shift</h3>
            <p>Critical: {compare?.morning?.critical ?? 0}</p>
            <p>Open: {compare?.morning?.open ?? 0}</p>
          </Card>
          <Card variant="analytics-card">
            <h3>Evening Shift</h3>
            <p>Critical: {compare?.evening?.critical ?? 0}</p>
            <p>Open: {compare?.evening?.open ?? 0}</p>
          </Card>
        </div>
      </Panel>
      <Panel title="Shift Handover History">
        <div className="ds-table-wrap">
          <table className="ds-table">
            <thead>
              <tr>
                <th>Shift</th>
                <th>Date</th>
                <th>Generated By</th>
                <th>Critical Issues</th>
                <th>Summary</th>
              </tr>
            </thead>
            <tbody>
              {items.map((row) => (
                <tr key={row.handover_id} className="ds-row" onClick={() => setSelected(row)}>
                  <td>{row.shift_label}</td>
                  <td className="ds-mono">{row.generated_at ? String(row.generated_at).slice(0, 16) : "—"}</td>
                  <td>{row.generated_by || "handover_agent"}</td>
                  <td>{row.critical_open_count}</td>
                  <td>{(row.summary_text || "").split("\n")[0]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>
      {selected ? (
        <Panel title={selected.shift_label || "Handover"} style={{ marginTop: 24 }}>
          <div className="ds-toolbar">
            <Button variant="ghost" onClick={() => onExport("json")}>
              Export Handover Report JSON
            </Button>
            <Button variant="ghost" onClick={() => onExport("pdf")}>
              Export Handover Report PDF
            </Button>
          </div>
          <pre className="ds-handover-summary">{selected.summary_text}</pre>
          <h3>Handover Timeline</h3>
          <ol className="ds-emergency-timeline">
            {(selected.timeline || []).map((item) => (
              <li key={`${item.time}-${item.event}`}>
                <time>{item.time}</time>
                <span>{item.event}</span>
              </li>
            ))}
          </ol>
          <h3>How this handover was generated</h3>
          <p>Data sources:</p>
          <ul className="ds-vision">
            <li>✓ {selected.explainability?.open_incidents ?? selected.open_incident_count} open incidents</li>
            <li>✓ {selected.explainability?.critical_incidents ?? selected.critical_open_count} Critical incident</li>
            <li>✓ {selected.explainability?.pending_reviews ?? selected.human_review_required} pending reviews</li>
            <li>✓ {selected.explainability?.overdue_verification ?? selected.awaiting_verification_overdue} overdue verification</li>
          </ul>
          <p className="ds-mono">{selected.explainability?.note}</p>
        </Panel>
      ) : null}
    </AppShell>
  );
}
